### ISSUE TITLE
Dependency question

### ISSUE THREAD

**Issue by nelson2005** [cpcloud/numbsql#134]
the dependencies say python >= 3.7, but I can't 'pip install' from pypi with 3.7.1.

It seems like the real requirement might be >= 3.7.8... is that the case?  Or is this a pypi issue?

**Comment by cpcloud** [comment]
Currently, the dependency is a minimum of Python 3.7.8 per https://github.com/cpcloud/numbsql/blob/master/pyproject.toml#L20.

It looks like this may not actually be an issue anymore. I'll put up a PR to lower the bound.

**Comment by cpcloud** [comment]
@nelson2005 Before I merge that PR, are you able to upgrade to a later version, say Python 3.8? I'm considering dropping support for Python 3.7 altogether.

**Comment by cpcloud** [comment]
Closed by #140

**Comment by nelson2005** [comment]
> Python

I'd love to upgrade but have users that cannot (or will not) upgrade for various reasons.  ☹️

So I'm stuck supporting a variety of versions... I suspect the user community will upgrade only when my company prohibits that version.

Thanks for relaxing the constraint

**Comment by nelson2005** [comment]
Just as a general dependency comment, I understand why you'd want to keep them as narrow as possible, but some permissiveness can be helpful.  For example, numba 0.54.1 has a [regression](https://github.com/numba/numba/issues/7573) that make it impossible for us to use so we've been unable to upgrade recently.

That being said, this is a great library (thanks!) and I can obviously work around such things. :)

**Comment by cpcloud** [comment]
@nelson2005 Let me investigate whether it's possible to use bounds. `numba` and `llvmlite` are tied, so that was why I initially pinned the versions.

**Comment by nelson2005** [comment]
hmm.... wouldn't installing numba automatically pull in the correct version of llvmlite due to numba's own dependencies?  Perhaps not, I'm a python packaging newbie

**Comment by cpcloud** [comment]
> hmm.... wouldn't installing numba automatically pull in the correct version of llvmlite due to numba's own dependencies? Perhaps not, I'm a python packaging newbie

Yes, but I'm using `llvmlite` in this library, so it needs to specified in `pyproject.toml`.

**Comment by nelson2005** [comment]
got it

**Comment by cpcloud** [comment]
@nelson2005 Are the versions #148 ok with you? I set them to the versions that I initially developed against.

**Comment by nelson2005** [comment]
I think so... we're using numba 0.53.1 now.  Thanks!

**Comment by cpcloud** [comment]
@nelson2005 Thanks!

I just merged #148, a new release will be posted to PyPI automatically when CI on `master` finishes.

**Comment by cpcloud** [comment]
@nelson2005 Release 4.0.6 is out.

**Comment by nelson2005** [comment]
Thanks!
