### ISSUE TITLE
Dependency updates

### ISSUE THREAD

**Issue by nelson2005** [cpcloud/numbsql#218]
I noticed the numpy requirement was bumped, but no code was changed... what's the thought there?

It's not a problem, I was just surprised when I updated numbsql and my numpy also got updated.

**Comment by cpcloud** [comment]
https://github.com/cpcloud/numbsql/pull/204

I cc'd you on that PR :)

**Comment by nelson2005** [comment]
Hah, I've been owned :)  closing.
